    "import warnings\n",
    "warnings.filterwarnings('ignore')\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "pd.set_option('display.max_columns', 500)\n",
    "pd.set_option('display.max_rows', 500)\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "import lightgbm as lgb\n",
    "from sklearn import preprocessing, metrics\n",
    "from sklearn.preprocessing import LabelEncoder\n",
    "import gc\n",
    "import os\n",
    "from datetime import datetime,timedelta\n",
    "from tqdm.notebook import tqdm\n",
    "from scipy.sparse import csr_matrix\n",
    "from google.colab import drive\n",
    "import joblib\n",
    "from sklearn.model_selection import KFold, GroupKFold, StratifiedKFold\n",
    "import math\n",
    "from math import ceil\n",
    "from datetime import datetime\n",
    "# drive.mount('/content/drive/')\n",
    "# os.chdir(\"drive/My Drive\")"
